default:
  image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/.gitlab-ci.yml

test-job1:
  stage: test
  script:
    - mvn test

build-job:
  stage: build
  script:
    - mvn test jar:jar


